[package]
name = "origami-window"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.14.5"
gdk = "0.14.2"
glib = "0.14.5"
gtk = "0.14.1"
origami-webview = {path="../origami-webview"}