[workspace]
members = [
    "packages/origami",
    "packages/origami-bridge",
    "packages/origami-generate",
    "packages/origami-sdk",
    "packages/origami-ui",
    "packages/origami-webview",
    "packages/origami-window",
    "examples/*"
]
