[package]
name = "origami-webview"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webkit2gtk = { version = "0.14", features = ["v2_26"] }
gio = "0.14.5"