[package]
name = "origami"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
origami-window = { path = "../origami-window" }
origami-webview = { path = "../origami-webview" }